version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./src/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js # bind mount - mongo-init.js in the mongo folder of the host machine is the same as the mongo-init.js file in the container's /docker-entrypoint-initdb.d
#      - ./src/mongo_data:/data/db # to persist data even after stopping and rerunning container / storing data outside of container
  server:
    image: backend-test
    ports:
      - 3000:3000
    build:
      dockerfile: test.Dockerfile # This will simply tell which dockerfile to read
    environment:
      NODE_ENV: test # not needed - set inline
      MONGODB_URI: mongodb://the_username:the_password@mongo:27017/the_database?retryWrites=true&w=majority
      TEST_MONGODB_URI: mongodb://the_username:the_password@mongo:27017/the_database_test?retryWrites=true&w=majority # THE port mapping - container port must be used!
      SECRET: abcd123
      PORT: 3000
#    volumes: # Declare the volume
#      - ./backend/src/:/usr/src/app/src/
    container_name: backend-test