name: backend pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        working-directory: ./backend
        run: npm install
      - name: test
        working-directory: ./backend
        run: npm run test
#      - name: lint
#        run: npm run eslint
#      - name: build
#        run: npm run build
#      - name: test
#        run: npm run test
#      - name: e2e tests
#        uses: cypress-io/github-action@v4
#        with:
#          build: npm run build
#          start: npm run start-prod
#          wait-on: http://localhost:5000 # changed from 5000